In [1]:
import pandas as pd

In [2]:
data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [5]:
df_duplicate = pd.concat([df,df.iloc[[2,5]]],ignore_index=True)

In [6]:
print(df_duplicate)

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0          101   25    Male  Cardiology  Nagpur           50000              5
1          102   45  Female   Neurology    Pune           35000              3
2          103   35    Male  Cardiology  Nagpur           60000              6
3          104   60  Female  Orthopedic  Mumbai           45000              4
4          105   50    Male   Neurology    Pune           30000              2
5          106   28  Female  Cardiology  Nagpur           55000              5
6          107   65    Male  Orthopedic  Mumbai           70000              7
7          108   40  Female   Neurology    Pune           40000              3
8          109   55    Male  Cardiology  Nagpur           65000              6
9          110   30  Female  Orthopedic  Mumbai           50000              4
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [7]:
# pd.concat() #Data_Frames ko Jodne ka kaam karta hai  
# iloc[[2,5]] row 2 aur row  5 selct karna  
# ignore_index = Ture --> index ko fresh numbering dega

In [8]:
# agar df 10 row hai aur hum df.iloc[[2,5]] se row add kar rahe hai toh total row kitni ho jayegi
#  12 rows
# aur kaunsi row duplicate hogi?

In [9]:
# duplicate() duplicate hai ya nhai
df_duplicate.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [10]:
df_duplicate[df_duplicate.duplicated()]

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [11]:
# df_duplicate.drop_duplicates()

In [12]:
df_clean = df_duplicate.drop_duplicates()

In [13]:
df_clean

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [14]:
df_clean.shape

(10, 7)

In [15]:
# duplicated() -- >duplicate identify karta hai
# drop_duplicate() -- > duplicxate ko remove kardeta hai

In [16]:
# agar patient 103 do baar hai so kya dono delete hoge kya

In [17]:
df_duplicate.duplicated(subset="Patient_ID")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [18]:
df_duplicate.drop_duplicates(subset="Patient_ID")

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [19]:
df_duplicate[df_duplicate.duplicated()]

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5