In [1]:
import pandas as pd

In [2]:
data = {
    "Student": ["Amit", "Neha", "Rahul", "Pooja"],
    "Marks": [85, 92, 76, 88],
    "City": ["Nagpur", "Pune", "Mumbai", "Nashik"]
}

In [3]:
df = pd.DataFrame(data, index=[101, 105, 110, 115])

In [4]:
df.loc[110]

Student     Rahul
Marks          76
City       Mumbai
Name: 110, dtype: object

In [5]:
df.iloc[2]

Student     Rahul
Marks          76
City       Mumbai
Name: 110, dtype: object

In [ ]:
df.loc[101] #label name

Student      Amit
Marks          85
City       Nagpur
Name: 101, dtype: object

In [ ]:
df.iloc[0]

Student      Amit
Marks          85
City       Nagpur
Name: 101, dtype: object

In [8]:
df.iloc[0 : 2]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune

In [9]:
print(df)

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [10]:
df.iloc[1 : 3]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai

In [ ]:
# iloc [start : stop] start include, stop excluded

In [13]:
df.iloc[1 : 4]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [14]:
df.iloc[:3]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai

In [15]:
df.iloc[1 : ]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [ ]:
# ek specific column ki first 3 values
df.iloc[ : 3,1]  # : 3 -- first 3 rows, 1 -- column ki postion

101    85
105    92
110    76
Name: Marks, dtype: int64