LOC & ILOC LOGIC BUILDING

In [1]:
import pandas as pd

In [2]:
data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105", "P106", "P107", "P108", "P109", "P110"],
    "Age": [45, 30, 55, 62, 28, 41, 50, 33, 47, 39],
    "City": ["Hyderabad", "Warangal", "Chennai", "Hyderabad", "Mumbai", "Warangal", "Hyderabad", "Chennai", "Hydearabd", "Mumbai"],
    "Surgery_Type": ["Cardiac", "Ortha", "Neuro", "Cardiac", "Ortho", "Neuro", "Cardiac", "Ortho", "Neuro", "Cardiac"],
    "Admission_Type": ["Planned", "Emergency", "Planned", "Planned", "Emergency", "Planned", "Emergency", "Planned","Planned", "Emergency"],
    "Operation_Duration_Min": [120, 60, 150, 90, 45, 110, 130, 70, 160, 50]
}

In [3]:
df=pd.DataFrame(data)

In [4]:
print(df)

  Patient_ID  Age       City Surgery_Type Admission_Type  \
0       P101   45  Hyderabad      Cardiac        Planned
1       P102   30   Warangal        Ortha      Emergency
2       P103   55    Chennai        Neuro        Planned
3       P104   62  Hyderabad      Cardiac        Planned
4       P105   28     Mumbai        Ortho      Emergency
5       P106   41   Warangal        Neuro        Planned
6       P107   50  Hyderabad      Cardiac      Emergency
7       P108   33    Chennai        Ortho        Planned
8       P109   47  Hydearabd        Neuro        Planned
9       P110   39     Mumbai      Cardiac      Emergency

   Operation_Duration_Min
0                     120
1                      60
2                     150
3                      90
4                      45
5                     110
6                     130
7                      70
8                     160
9                      50

Q1. Using loc, display only the patients whose City is
"Hyderabad" OR "Warangal". (Display only:Patient_ID,Age,City,Surgery_Type)

In [10]:
df.loc[(df["City"] == "Hyderabad") | (df["City"] == "Warangal"),[ "Patient_ID", "Age", "City", "Surgery_Type"]]

  Patient_ID  Age       City Surgery_Type
0       P101   45  Hyderabad      Cardiac
1       P102   30   Warangal        Ortha
3       P104   62  Hyderabad      Cardiac
5       P106   41   Warangal        Neuro
6       P107   50  Hyderabad      Cardiac

Q2. Using iloc, display:• Rows 2 to 7,• Only columns 1, 3 and 5
 Remember: iloc uses POSITION, not column names.

In [11]:
df.iloc[2:8, [1, 3, 5]]

   Age Surgery_Type  Operation_Duration_Min
2   55        Neuro                     150
3   62      Cardiac                      90
4   28        Ortho                      45
5   41        Neuro                     110
6   50      Cardiac                     130
7   33        Ortho                      70

Q3.Using loc, display patients whose:• Age is greater than 40 AND • Admission_Type is "Planned"
Display only: Patient_ID, Age, Surgery_Type, Admission_Type
.

In [12]:
df.loc[(df["Age"] > 40) & (df["Admission_Type"] == "Planned"), ["Patient_ID", "Age", "Surgery_Type", "Admission_Type"] ]

  Patient_ID  Age Surgery_Type Admission_Type
0       P101   45      Cardiac        Planned
2       P103   55        Neuro        Planned
3       P104   62      Cardiac        Planned
5       P106   41        Neuro        Planned
8       P109   47        Neuro        Planned

Q4. Using loc, find patients from Hyderabad whose Operation_Duration_Min is greater than 100.
Display only: Patient_ID, City, Operation_Duration_Min

In [19]:
df.loc[(df["City"] == "Hyderabad") & (df["Operation_Duration_Min"] > 100), ["Patient_ID", "City", "Operation_Duration_Min"] ]

  Patient_ID       City  Operation_Duration_Min
0       P101  Hyderabad                     120
6       P107  Hyderabad                     130

Q5. Using iloc, display:• Every alternate row starting from the first row, • Only the first 4 columns
Think about: row slicing + column slicing

In [24]:
df.iloc[::2, :4]

  Patient_ID  Age       City Surgery_Type
0       P101   45  Hyderabad      Cardiac
2       P103   55    Chennai        Neuro
4       P105   28     Mumbai        Ortho
6       P107   50  Hyderabad      Cardiac
8       P109   47  Hydearabd        Neuro

Q6. Without using idxmax(), idxmin(), sort_values() or any other function:
Using only loc and iloc, display the patient at index label 8 with: Patient_ID, City, Surgery_Type, Age
Then display the same patient's information using iloc.

In [20]:
print(df)

  Patient_ID  Age       City Surgery_Type Admission_Type  \
0       P101   45  Hyderabad      Cardiac        Planned
1       P102   30   Warangal        Ortha      Emergency
2       P103   55    Chennai        Neuro        Planned
3       P104   62  Hyderabad      Cardiac        Planned
4       P105   28     Mumbai        Ortho      Emergency
5       P106   41   Warangal        Neuro        Planned
6       P107   50  Hyderabad      Cardiac      Emergency
7       P108   33    Chennai        Ortho        Planned
8       P109   47  Hydearabd        Neuro        Planned
9       P110   39     Mumbai      Cardiac      Emergency

   Operation_Duration_Min
0                     120
1                      60
2                     150
3                      90
4                      45
5                     110
6                     130
7                      70
8                     160
9                      50

In [25]:
df.loc[0]

Patient_ID                     P101
Age                              45
City                      Hyderabad
Surgery_Type                Cardiac
Admission_Type              Planned
Operation_Duration_Min          120
Name: 0, dtype: object

In [26]:
df.iloc[0]

Patient_ID                     P101
Age                              45
City                      Hyderabad
Surgery_Type                Cardiac
Admission_Type              Planned
Operation_Duration_Min          120
Name: 0, dtype: object